## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
0,0,Arraial Do Cabo,BR,-22.9661,-42.0278,77.00,78,0,17.27,clear sky,2021-01-17 23:00:09
1,1,Mayya,RU,61.7333,130.2811,-58.00,51,90,4.63,fog,2021-01-17 23:03:19
2,2,Puerto Ayora,EC,-0.7393,-90.3518,80.60,69,75,17.27,broken clouds,2021-01-17 23:03:19
3,3,Srednekolymsk,RU,67.4500,153.6833,-41.10,81,40,3.00,scattered clouds,2021-01-17 23:03:19
4,4,Lagoa,PT,39.0500,-27.9833,62.04,82,80,26.84,light rain,2021-01-17 23:02:34

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.

preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
0,0,Arraial Do Cabo,BR,-22.9661,-42.0278,77.00,78,0,17.27,clear sky,2021-01-17 23:00:09
2,2,Puerto Ayora,EC,-0.7393,-90.3518,80.60,69,75,17.27,broken clouds,2021-01-17 23:03:19
6,6,Rikitea,PF,-23.1203,-134.9692,78.96,74,15,14.05,few clouds,2021-01-17 23:03:20
13,13,Dingle,PH,10.9995,122.6711,75.36,92,100,7.92,overcast clouds,2021-01-17 23:03:21
20,20,Mahebourg,MU,-20.4081,57.7000,78.80,78,75,11.50,broken clouds,2021-01-17 23:01:28
22,22,Port-Gentil,GA,-0.7193,8.7815,80.60,89,75,2.30,moderate rain,2021-01-17 23:03:23
25,25,Avarua,CK,-21.2078,-159.7750,86.00,66,20,9.22,few clouds,2021-01-17 23:03:23
27,27,Hithadhoo,MV,-0.6000,73.0833,80.80,70,82,6.93,broken clouds,2021-01-17 23:03:24
29,29,Pochutla,MX,15.7432,-96.4661,82.40,69,40,8.05,light rain,2021-01-17 23:03:24
30,30,Atuona,PF,-9.8000,-139.0333,78.57,78,47,14.81,scattered clouds,2021-01-17 23:03:24

In [5]:
# 4a. Determine if there are any empty rows.

preferred_cities_df.count()

City_ID                180
City                   180
Country                180
Lat                    180
Lng                    180
Max Temp               180
Humidity               180
Cloudiness             180
Wind Speed             180
Current Description    180
Date                   180
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
preferred_cities_df.dropna()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
0,0,Arraial Do Cabo,BR,-22.9661,-42.0278,77.00,78,0,17.27,clear sky,2021-01-17 23:00:09
2,2,Puerto Ayora,EC,-0.7393,-90.3518,80.60,69,75,17.27,broken clouds,2021-01-17 23:03:19
6,6,Rikitea,PF,-23.1203,-134.9692,78.96,74,15,14.05,few clouds,2021-01-17 23:03:20
13,13,Dingle,PH,10.9995,122.6711,75.36,92,100,7.92,overcast clouds,2021-01-17 23:03:21
20,20,Mahebourg,MU,-20.4081,57.7000,78.80,78,75,11.50,broken clouds,2021-01-17 23:01:28
...,...,...,...,...,...,...,...,...,...,...,...
668,668,Kango,GA,0.1943,10.0951,75.04,94,75,1.23,broken clouds,2021-01-17 23:05:40
675,675,Wahiawa,US,21.5028,-158.0236,78.01,88,90,8.63,overcast clouds,2021-01-17 23:03:25
676,676,Moron,AR,-34.6534,-58.6198,75.99,45,0,3.00,clear sky,2021-01-17 23:05:42
680,680,Lucea,JM,18.4510,-78.1736,80.60,74,20,14.97,few clouds,2021-01-17 23:05:36
696,696,Kempsey,AU,-31.0833,152.8333,77.00,65,98,3.00,overcast clouds,2021-01-17 23:03:46

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Arraial Do Cabo,BR,77.00,clear sky,-22.9661,-42.0278,
2,Puerto Ayora,EC,80.60,broken clouds,-0.7393,-90.3518,
6,Rikitea,PF,78.96,few clouds,-23.1203,-134.9692,
13,Dingle,PH,75.36,overcast clouds,10.9995,122.6711,
20,Mahebourg,MU,78.80,broken clouds,-20.4081,57.7000,
22,Port-Gentil,GA,80.60,moderate rain,-0.7193,8.7815,
25,Avarua,CK,86.00,few clouds,-21.2078,-159.7750,
27,Hithadhoo,MV,80.80,broken clouds,-0.6000,73.0833,
29,Pochutla,MX,82.40,light rain,15.7432,-96.4661,
30,Atuona,PF,78.57,scattered clouds,-9.8000,-139.0333,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # 6c. Get latitude and longitude from DataFrame
    params["location"] = f"{lat},{lng}"

     # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
   
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [9]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df.head()

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Arraial Do Cabo,BR,77.00,clear sky,-22.9661,-42.0278,Pousada Porto Praia
2,Puerto Ayora,EC,80.60,broken clouds,-0.7393,-90.3518,Castillo Galapagos
6,Rikitea,PF,78.96,few clouds,-23.1203,-134.9692,Pension Maro'i
13,Dingle,PH,75.36,overcast clouds,10.9995,122.6711,SEGAYA PROPERTY
20,Mahebourg,MU,78.80,broken clouds,-20.4081,57.7000,Shandrani Beachcomber Resort & Spa

In [10]:
# 8a. Create the output File (CSV)

output_data_file = "Vacation_Search/WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv

hotel_df.to_csv(output_data_file, index_label="City_ID")

In [14]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [13]:
# 11a. Add a marker layer for each city to the map. 

locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)


# 11b. Display the figure

fig

Figure(layout=FigureLayout(height='420px'))